apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-vanilla-server
spec:
  selector:
    matchLabels:
      app: mc-vanilla-server
  template:
    metadata:
      labels:
        app: mc-vanilla-server
    spec:
      containers:
        - image: itzg/minecraft-server
          name: mc-vanilla-server
          env:
            - name: EULA
              value: "true"
          ports:
            - containerPort: 25565
              name: main
          readinessProbe:
            exec:
              command:
                - mcstatus
                - localhost
                - ping
            initialDelaySeconds: 90
            periodSeconds: 90
          livenessProbe:
            exec:
              command:
                - mcstatus
                - localhost
                - ping
            initialDelaySeconds: 90
            periodSeconds: 90
          volumeMounts:
            - name: mc-data
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 2Gi
      volumes:
        - name: mc-data
          emptyDir: {}
